### ISSUE TITLE
File ./math/fibonacci.cpp tidak lulus testcase pada fungsi test()

### ISSUE THREAD

**Issue by Albtony** [bellshade/CPP#64]
🐞 Problem
File `./math/fibonacci.cpp` terdapat typo dan tidak lulus testcase pada fungsi `test()`;
berikut hasil compile dan run file tsb:
![image](https://user-images.githubusercontent.com/78489357/194709352-db346838-6bd2-40a5-9b0b-3f93177b1d68.png)
apabila `line 37` dicomment maka akan muncul:
![image](https://user-images.githubusercontent.com/78489357/194709415-24c54bcc-1720-4b98-a43d-da77605cc2ba.png)

🎯 How to Replicate?
- clone repo
- compile dan run `.\CPP\math\fibonacci.cpp`

💡 Possible solutions
memperbaiki base case menjadi 
```cp
  if (n == 0) {
    return 0;
  } else if (n == 1) {
    return 1;
  }
```

**Comment by slowy07** [comment]
sudah diperbaiki, issue akan di close
