### ISSUE TITLE
Ide konten Variable Reference dan Pointer dalam c++

### ISSUE THREAD

**Issue by Aldhanekaa** [bellshade/CPP#9]
# Ide konten Reference dan Pointer (variable) dalam c++
Halo semua, sama kenal! Tampaknya ada kekurangan pada konten variable, saya tidak melihat mengenai variable `reference` dan `pointer` dalam dokumentasi di repo ini.

---

**ToDo:**
- [ ] Reference Variable
- [ ] Pointer Variable

**Comment by Aldhanekaa** [comment]
Jika teman-teman berkenan, saya bersedia mengerjakan bagian ini :D 
Terimakasih.

**Comment by slowy07** [comment]
dipersilahkan kak @Aldhanekaa :100:

**Comment by arifyunando** [comment]
Materi ini sudah dalam Pull Request dan sedang dalam review. Maka issue ini saya close. Thank you
